#开发环境
server:
  port: 8081

spring:
  datasource:
    username: analysis
    password: goldwind2018!
    url: jdbc:mysql://10.12.9.34:3306/gain_external_data?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false #开发时关闭缓存,不然没法看到实时页面
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html