#生产环境
server:
  port: 8443
  ssl:
    key-store: classpath:2678385_o2xygen.fun.pfx
    key-store-password: vL1UE0LE
    keyStoreType: PKCS12

spring:
  datasource:
    username: analysis
    password: goldwind2018!
    url: jdbc:mysql://10.12.9.34:3306/gain_external_data?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.com.goldwind.kis.entity