insert into `t_key_info` values(NULL,'安全滑轨','rigid anchor line',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'安全滑块','fall arrester',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'安全帽','safety helmet',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'安全绳','safety lanyard',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'安全绳','safety line',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'安全锁扣','guided type fall arrester',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'安全鞋','safety shoes',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'安全衣','full-body harness',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'导向跌落保护装置','guided type fall arresters',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'电绝缘手套','electrical insulating gloves',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'耳塞','earplug',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'耳罩','ear plug',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'防尘口罩','dust mask',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'防护等级','degrees of protection',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'防护耳塞','hearing protection ear plug',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'防护手套','work gloves',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'防护网','protective cover',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'防护眼镜','safety goggles/goggles',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'防护罩','protective cover',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'防滑耐磨手套','Wear-resistant antiskid gloves',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'防静电手套','antistatic gloves',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'防坠落滑动器','guided type fall arrester',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'防坠器','fall arrester',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'刚性铰链','rigid anchor line',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'个人防护用品','personal protective equipment (PPE)',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'工业安全帽','Industrial safety helmets',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'工作服','workwear',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'工作鞋','work shoes',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'护面罩','face shield',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'护目镜','goggle',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'连结绳索','Lanyards ',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'能量吸收器','Energy absorbers',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'全身保护成套装置 ','Full body harnesses ',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'全身背负式安全带','full body harness',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'全身式安全带','full body harness',NULL,'','','风电','HSE','PPE');
insert into `t_key_info` values(NULL,'备用电源','backup power supply',NULL,'','','风电','风机','变桨系统');
insert into `t_key_info` values(NULL,'闭环频率控制','closed-loop frequency control',NULL,'','','风电','风机','变桨系统');
insert into `t_key_info` values(NULL,'变桨','pitch',NULL,'','','风电','风机','变桨系统');
insert into `t_key_info` values(NULL,'变桨挡块','pitch stopper',NULL,'','','风电','风机','变桨系统');
insert into `t_key_info` values(NULL,'变桨电机','pitch motor',NULL,'','','风电','风机','变桨系统');
insert into `t_key_info` values(NULL,'变桨电机驱动器','inverter',NULL,'','','风电','风机','变桨系统');
insert into `t_key_info` values(NULL,'变桨减速器','pitch gearbox',NULL,'','','风电','风机','变桨系统');
insert into `t_key_info` values(NULL,'变桨控制柜','pitch box',NULL,'','','风电','风机','变桨系统');
insert into `t_key_info` values(NULL,'变桨控制柜','pitch control cabinet',NULL,'','','风电','风机','变桨系统');
insert into `t_key_info` values(NULL,'变桨控制系统','pitch control system',NULL,'','','风电','风机','变桨系统');
insert into `t_key_info` values(NULL,'变桨驱动','pitch drive',NULL,'','','风电','风机','变桨系统');
insert into `t_key_info` values(NULL,'变桨驱动器','inverter',NULL,'','','风电','风机','变桨系统');
insert into `t_key_info` values(NULL,'变桨系统','pitch system',NULL,'','','风电','风机','变桨系统');
insert into `t_key_info` values(NULL,'变桨轴承','pitch bearing',NULL,'','','风电','风机','变桨系统')
